### ISSUE TITLE
Download of pdf file fails

### ISSUE THREAD

**Issue by Shreeshrii** [tshrinivasan/OCR4wikisource#107]
```
INFO:root:Operating System = "Ubuntu 16.04.4 LTS"

...

INFO:__main__:Original URL = http://sanskritdocuments.org/doc_trial/fortransfer/girdhari/shArikApUjA_devIrahasyaSCAN.pdf
INFO:__main__:File Name = shArikApUjA_devIrahasyaSCAN.pdf
INFO:__main__:File Type = pdf
INFO:__main__:Created Temp folder OCR-shArikApUjA_devIrahasyaSCAN.pdf-temp-2018-05-22-08-30-09


Downloading the file shArikApUjA_devIrahasyaSCAN.pdf


INFO:__main__:Downloading the file shArikApUjA_devIrahasyaSCAN.pdf
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): sanskritdocuments.org
Traceback (most recent call last):
  File "do_ocr_jpg.py", line 137, in <module>
    total_length = int(r.headers.get('content-length'))
TypeError: int() argument must be a string or a number, not 'NoneType'
ubuntu@tesseract-ocr:~/OCR4wikisource$

```

**Comment by Shreeshrii** [comment]
```
INFO:__main__:Running do_ocr.py 1.54
INFO:root:Operating System = "Ubuntu 14.04.5 LTS"

...

INFO:__main__:Original URL = http://sanskritdocuments.org/doc_trial/fortransfer/girdhari/shArikApUjA_devIrahasyaSCAN.pdf
INFO:__main__:File Name = shArikApUjA_devIrahasyaSCAN.pdf
INFO:__main__:File Type = pdf
INFO:__main__:Created Temp folder OCR-shArikApUjA_devIrahasyaSCAN.pdf-temp-2018-05-22-02-23-30


Downloading the file shArikApUjA_devIrahasyaSCAN.pdf


INFO:__main__:Downloading the file shArikApUjA_devIrahasyaSCAN.pdf
INFO:urllib3.connectionpool:Starting new HTTP connection (1): sanskritdocuments.org
Traceback (most recent call last):
  File "do_ocr_jpg.py", line 137, in <module>
    total_length = int(r.headers.get('content-length'))
TypeError: int() argument must be a string or a number, not 'NoneType'

```

**Comment by Shreeshrii** [comment]
Tried on two different machines. Same error.

**Comment by tshrinivasan** [comment]
try uploading the same file to commons and use the url from commons and
share the result.

**Comment by Shreeshrii** [comment]
INFO:__main__:Original URL = https://commons.wikimedia.org/wiki/File:ShArikApUjA_devIrahasyaSCAN.pdf
INFO:__main__:File Name = File:ShArikApUjA_devIrahasyaSCAN.pdf
INFO:__main__:File Type = pdf
INFO:__main__:Created Temp folder OCR-File:ShArikApUjA_devIrahasyaSCAN.pdf-temp-2018-05-22-08-52-57


Downloading the file File:ShArikApUjA_devIrahasyaSCAN.pdf


INFO:__main__:Downloading the file File:ShArikApUjA_devIrahasyaSCAN.pdf
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): commons.wikimedia.org
Traceback (most recent call last):
  File "do_ocr_jpg.py", line 137, in <module>
    total_length = int(r.headers.get('content-length'))
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by tshrinivasan** [comment]
Try with this url

https://upload.wikimedia.org/wikipedia/commons/1/17/ShArikApUjA_devIrahasyaSCAN.pdf

**Comment by Shreeshrii** [comment]
Thanks, this URL works fine.

It seems that some servers do NOT provide content-length. Is it possible to modify the script to handle such cases (not display the progress bar for them but download the file).

**Comment by Shreeshrii** [comment]
Removed the progress bar, it works now for my usercase.

```
            #Download the file

            r = requests.get(url, stream=True)
            with open(filename, 'wb') as f:
                        for chunk in r.iter_content(chunk_size=1024):
                                    if chunk:
                                                f.write(chunk)
                                                f.flush()
```
