### ISSUE TITLE
wikitools.page.BadTitle error

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#13]
File URL - https://upload.wikimedia.org/wikipedia/commons/b/b4/%E0%AE%95%E0%AE%B2%E0%AF%88%E0%AE%95%E0%AF%8D_%E0%AE%95%E0%AE%B3%E0%AE%9E%E0%AF%8D%E0%AE%9A%E0%AE%BF%E0%AE%AF%E0%AE%AE%E0%AF%8D_%E0%AE%85%E0%AE%AE%E0%AF%8D%E0%AE%AE%E0%AE%BE%E0%AE%B2%E0%AE%A9-%E0%AE%85%E0%AE%B0%E0%AF%87%E0%AE%AA%E0%AE%BF%E0%AE%AF%E0%AE%BE.pdf

WS index link - https://ta.wikisource.org/s/3vf

Downloads and splits pages. But, shows error when running mediawiki_uploader.py

I started uploading from page 14. No page was created successfully.

Error log: 

Uploading content for text_for_page_00014.txt
Traceback (most recent call last):
  File "mediawiki_uploader.py", line 108, in <module>
    page = wikitools.Page(wiki,"Page:"+ pagename, followRedir=True)
  File "/usr/local/lib/python2.7/dist-packages/wikitools/page.py", line 109, in **init**
    self.setPageInfo()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/page.py", line 152, in setPageInfo
    raise BadTitle(self.title)
wikitools.page.BadTitle: Page:%E0%AE%95%E0%AE%B2%E0%AF%88%E0%AE%95%E0%AF%8D %E0%AE%95%E0%AE%B3%E0%AE%9E%E0%AF%8D%E0%AE%9A%E0%AE%BF%E0%AE%AF%E0%AE%AE%E0%AF%8D %E0%AE%85%E0%AE%AE%E0%AF%8D%E0%AE%AE%E0%AE%BE%E0%AE%B2%E0%AE%A9-%E0%AE%85%E0%AE%B0%E0%AF%87%E0%AE%AA%E0%AE%BF%E0%AE%AF%E0%AE%BE.pdf/14

**Comment by ravidreams** [comment]
Confirming: after testing, this is found fixed in Version 1.27 .
