### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by jayantanth** [tshrinivasan/OCR4wikisource#52]
# 

INFO:**main**:

uploading page_00001.pdf to google Drive. 
INFO:**main**:Running gdput.py -t ocr -f   0B1OpcVV-_vRSSzZIeElmRE9fMlE page_00004.pdf | tee page_00004.log
Traceback (most recent call last):
  File "/usr/local/bin/gdput.py", line 252, in <module>
Uploading file: page_00001.pdf
File size: 13.8KB
    response = puter.run()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 120, in run
    result = getattr(self, self.target_type + "_put")()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 505, in ocr_put
    return self.generic_put(True)
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 485, in generic_put
    service_response = request.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&convert=true&alt=json returned "Internal Error">
INFO:__main__:
# 

[do_ocr_2016-02-07-21-05-15_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/128453/do_ocr_2016-02-07-21-05-15_log.txt)
[do_ocr_2016-02-09-00-27-57_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/128452/do_ocr_2016-02-09-00-27-57_log.txt)
[do_ocr_2016-02-12-23-57-04_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/128454/do_ocr_2016-02-12-23-57-04_log.txt)
[do_ocr_2016-02-13-00-05-37_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/128457/do_ocr_2016-02-13-00-05-37_log.txt)

**Comment by tshrinivasan** [comment]
Some issue with google connectivity.

Is this happening to all files?

are the same files uploaded after some time?

**Comment by jayantanth** [comment]
My other all files are working fine , no issue in other file. This error comes in a specific file, the link is

https://upload.wikimedia.org/wikipedia/commons/a/a5/%E0%A6%AC%E0%A7%8D%E0%A6%B0%E0%A6%B9%E0%A7%8D%E0%A6%AE%E0%A6%BE%E0%A6%A3%E0%A7%8D%E0%A6%A1%E0%A6%AA%E0%A7%81%E0%A6%B0%E0%A6%BE%E0%A6%A3%E0%A6%AE%E0%A7%8D%E2%80%8C.pdf

The file name with a complex script in Bengali, no file file uploaded in Google Drive. I have tried 4 times. Found the same error in each page. No internet connectivity issue. Same  time I was running this script in 4 folder in parallel.
