### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#69]
[Errno 111] Connection refused.

Page creation stops midway. Had to manually run mediawiki_uploader.py to upload remaining pages.

Uploading content for text_for_page_00257.txt
Traceback (most recent call last):
File "mediawiki_uploader.py", line 224, in <module>
    page.edit(text=content,summary=edit_summary,bot="True")
  File "/usr/local/lib/python2.7/dist-packages/wikitools/page.py", line 623, in edit
    result = req.query()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/api.py", line 158, in query
    rawdata = self.__getRaw()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/api.py", line 265, in __getRaw
    data = self.opener.open(self.request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by tshrinivasan** [comment]
This seems some network issue.

Is this happens for any other file or any other time?

**Comment by ravidreams** [comment]
No. Will report if the error is found again.

**Comment by tshrinivasan** [comment]
closing this for now.

Reopen if the same issue happens again.
