### ISSUE TITLE
Upload freezes

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#9]
File url - https://upload.wikimedia.org/wikipedia/commons/a/a5/%E0%A6%AC%E0%A7%8D%E0%A6%B0%E0%A6%B9%E0%A7%8D%E0%A6%AE%E0%A6%BE%E0%A6%A3%E0%A7%8D%E0%A6%A1%E0%A6%AA%E0%A7%81%E0%A6%B0%E0%A6%BE%E0%A6%A3%E0%A6%AE%E0%A7%8D%E2%80%8C.pdf

WS URL - https://bn.wikisource.org/wiki/%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A7%8D%E0%A6%98%E0%A6%A3%E0%A7%8D%E0%A6%9F:%E0%A6%AC%E0%A7%8D%E0%A6%B0%E0%A6%B9%E0%A7%8D%E0%A6%AE%E0%A6%BE%E0%A6%A3%E0%A7%8D%E0%A6%A1%E0%A6%AA%E0%A7%81%E0%A6%B0%E0%A6%BE%E0%A6%A3%E0%A6%AE%E0%A7%8D%E2%80%8C.pdf

File downloaded, split into 752 single column pdf files. But, it says uploading file 1 of 360 for more than 3 hours and nothing happened. The internet connection was intact. 

Downloading the file ব্রহ্মাণ্ডপুরাণম্‌.pdf

30598/30598 - 00:00:16
Aligining the Pages of PDF file. 

Spliting the PDF into single pages. 

Joining the PDF files ...

Creating a folder in Google Drive to upload files 

Folder Name : OCR-ব্রহ্মাণ্ডপুরাণম্‌.pdf-temp-2015-12-28-17-01-37

id: 0B9amQol3ByIjU1U2dGVsN05FYU0
drive view: https://drive.google.com/drive/folders/0B9amQol3ByIjU1U2dGVsN05FYU0
folder view: https://docs.google.com/folderview?id=0B9amQol3ByIjU1U2dGVsN05FYU0&usp=drivesdk

uploading page_00001.pdf to google Drive. File 1 of 376

**Comment by ravidreams** [comment]
Tried again in another system. Same error. 

On interrupting by CTRL+C, got following message:

uploading page_00001.pdf to google Drive. File 1 of 376 

^CTraceback (most recent call last):
  File "/usr/local/bin/gdput.py", line 252, in <module>
    response = puter.run()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 117, in run
    result = getattr(self, self.target_type + "_put")()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 481, in ocr_put
    return self.generic_put(True)
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 453, in generic_put
    status, service_response = request.next_chunk(num_retries=10)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 873, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
KeyboardInterrupt
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
Moving the file page_00001.pdf to the folder OCR-ব্রহ্মাণ্ডপুরাণম্‌.pdf-temp-2016-01-04-20-29-43

**Comment by jayantanth** [comment]
Tried this file again with version V1.42, I am sharing the message only page 44, this error message comes for each page.

# 

INFO:**main**:

uploading page_00044.pdf to google Drive. 
INFO:**main**:Running gdput.py -t ocr -f   0B1OpcVV-_vRSWi1SbmtsaHVGU28 page_00044.pdf | tee page_00044.log
Traceback (most recent call last):
Uploading file: page_00044.pdf
File size: 83.1KB
  File "/usr/local/bin/gdput.py", line 252, in <module>
    response = puter.run()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 120, in run
    result = getattr(self, self.target_type + "_put")()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 505, in ocr_put
    return self.generic_put(True)
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 485, in generic_put
    service_response = request.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&convert=true&alt=json returned "Internal Error">
INFO:__main__:

# 

[do_ocr_2016-02-07-21-05-15_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/120754/do_ocr_2016-02-07-21-05-15_log.txt)

**Comment by tshrinivasan** [comment]
reported here - https://github.com/tienfuc/gdcmdtools/issues/95
